name: Trivy Vulnerability Scan

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  scan:
    runs-on: ubuntu-latest

    steps:
      - name: Check out the code
        uses: actions/checkout@v3

      - name: Run Trivy Vulnerability Scanner
        uses: aquasecurity/trivy-action@v0.5.0
        with:
          scan-type: 'fs'              # 'fs' scans the local filesystem (code base)
          severity: 'HIGH,CRITICAL'     # Only high or critical severity vulnerabilities will be reported
          ignore-unfixed: true          # Ignore vulnerabilities with no fix available
